wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-db -O aflw-db.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-facedbsql-src -O aflw-facedbsql-src.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-gui-src -O aflw-gui-src.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-0 -O aflw-images-0.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-2 -O aflw-images-2.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-3 -O aflw-images-3.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-matlab -O aflw-matlab.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-gui-bin-win32 -O aflw-gui-bin-win32.zip
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-facedetector -O aflw-facedetector.tar.gz
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-db-md5 -O aflw-db.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-facedbsql-src-md5 -O aflw-facedbsql-src.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-gui-src-md5 -O aflw-gui-src.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-0-md5 -O aflw-images-0.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-2-md5 -O aflw-images-2.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-images-3-md5 -O aflw-images-3.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-matlab-md5 -O aflw-matlab.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-gui-bin-win32-md5 -O aflw-gui-bin-win32.zip.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=aflw-facedetector-md5 -O aflw-facedetector.tar.gz.md5
wget -c --post-data "access_login=zhonghx14@mails.tsinghua.edu.cn&access_password=WiwOHDzG" http://lrs.icg.tugraz.at/research/aflw/downloads.php?file=hashes-md5 -O hashes.md5
